### PR TITLE
Handle an :infinity expiration in multilevel replication.

### LINKED ISSUE #34: Multilevel Cache: replicate/2 is attempting to subtract from :infinity
## Environment

Elixir version (elixir -v): Elixir 1.7.4 (compiled with Erlang/OTP 21)
Nebulex version (mix deps): 1.0.0
Operating system: Debian Stretch

## Expected behavior
Fetching a key from the cache should return nil or an already cached value.

`Cache.get({:get_route, ~D[2018-12-05], "1", [solver_settings: nil]})`

## Actual behavior
```
Last message (from #PID<0.3307.3>): {:get_route, ~D[2018-12-05], "1", [solver_settings: nil]}
20:14:36.594 [info] Converted exit {{:badarith, [{:erlang, :-, [:infinity, 1544040876], []}, {Nebulex.Adapters.Multilevel, :replicate, 2, [file: 'lib/nebulex/adapters/multilevel.ex', line: 417]}, {Enum, :"-reduce/3-lists^foldl/2-0-", 3, [file: 'lib/enum.ex', line: 1925]}, {Nebulex.Cache.Object, :get, 3, [file: 'lib/nebulex/cache/object.ex', line: 12]}, {Cache, :with_hooks, 3, [file: 'lib/cache.ex', line: 2]}, {Routes.Manager, :handle_call, 3, [file: 'lib/routes/manager.ex', line: 38]}, {:gen_server, :try_handle_call, 4, [file: 'gen_server.erl', line: 661]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 690]}]}, {GenServer, :call, [Routes.Manager, {:get_route, ~D[2018-12-05], "1", [solver_settings: nil]}, :infinity]}} to 500 response
20:14:36.597 [error] #PID<0.3307.3> running Api.Endpoint (connection #PID<0.3306.3>, stream id 1) terminated
Server: localhost:80 (http)
Request: POST /graphql
** (exit) exited in: GenServer.call(Routes.Manager, {:get_route, ~D[2018-12-05], "1", [solver_settings: nil]}, :infinity)
    ** (EXIT) an exception was raised:
        ** (ArithmeticError) bad argument in arithmetic expression
            :erlang.-(:infinity, 1544040876)
            (nebulex) lib/nebulex/adapters/multilevel.ex:417: Nebulex.Adapters.Multilevel.replicate/2
            (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
            (nebulex) lib/nebulex/cache/object.ex:12: Nebulex.Cache.Object.get/3
            (db) lib/cache.ex:2: Cache.with_hooks/3
            (app) lib/routes/manager.ex:38: Routes.Manager.handle_call/3
            (stdlib) gen_server.erl:661: :gen_server.try_handle_call/4
            (stdlib) gen_server.erl:690: :gen_server.handle_msg/6
```

## More information
```
defp replicate(cache, %Object{expire_at: expire_at} = object) do
    object =
      if expire_at,
        do: %{object | expire_at: expire_at - DateTime.to_unix(DateTime.utc_now())},
        else: object

    true = cache.__adapter__.set(cache, object, [])
    object
  end
```

The above function is called to replicate from the L2 to the L1 cache, but the expire_at is set to `:infinity` on the Nebulex.Object struct. I am attempting to use a two level cache with L1 as Nebulex.Adapter.Local and L2 as NebulexRedisAdapter.

### PR DESCRIPTION
**Pull request by sdost**
I wrote another matching function to catch the :infinity expire_at value and simply pass through the object. This fixes #34.

### CODE REVIEW

File: lib/nebulex/adapters/multilevel.ex [hunk 1]
```diff
@@ -411,6 +411,11 @@ defmodule Nebulex.Adapters.Multilevel do
     |> Enum.reduce(object, &replicate(&1, &2))
   end
 
+  defp replicate(cache, %Object{expire_at: :infinity} = object) do
```
Comment (cabol) [inline lib/nebulex/adapters/multilevel.ex]: I think patter-match should be against `nil` instead of `:infinity` (according the `Nebulex.Object` struct). Otherwise, we should check why `:infinity` is being set in the object.

Comment (sdost) [reply lib/nebulex/adapters/multilevel.ex]: Well...`nil` would be handled by the original function. As far as where `:infinity` is coming from, thats a good question.

Comment (sdost) [reply lib/nebulex/adapters/multilevel.ex]: I would suggest doing a search in the repo for `:infinity` because there seem to be some things which use `nil` and some which use `:infinity`.

Comment (cabol) [reply lib/nebulex/adapters/multilevel.ex]: Yeah, meanwhile, let's merge this PR, it fixes the issue clearly, then I will find where the `:infinity` is coming from. Thanks for your contribution :) !!
